### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by adityanurdin** [BeefoIO/proxmox-client#4]
![{ACA52475-B460-461F-B00C-9B98F51B5543} png](https://user-images.githubusercontent.com/37808974/93007064-4b8e4e80-f58e-11ea-89df-834b45828481.jpg)

**Comment by BeefoIO** [comment]
could you send me the code where you execute the function?

**Comment by adityanurdin** [comment]
I'm using a javascript framework (AdonisJs), I'm just following your example code

this is my controller, by default adonisJs V5 use typescript
![proxmox-client-error](https://user-images.githubusercontent.com/37808974/93031427-e81b2400-f654-11ea-84c0-fa78afca694d.jpg)

**Comment by BeefoIO** [comment]
thanks, i will fix this later today and push it

**Comment by adityanurdin** [comment]
I really appreciate that, thank you

**Comment by BeefoIO** [comment]
sorry for the late response. I pushed the fix to npm so you can do 'npm update proxmox-client'
